### ISSUE TITLE
Ver datos del clima???

### ISSUE THREAD

**Issue by Juan2005** [opalenzuela/opendomo-weather#8]
Estoy comenzando con Opendomo, quisiera saber si es posible tomar datos del clima y presentarlos en pantalla. Ejemplo: actualizar la temperatura exterior cada 1 hora.
Por lo que estuve viendo el odweather esta bien instalado pero no se como ver datos con el mismo.
Gracias por la respuesta que me puedan brindar.

**Comment by opalenzuela** [comment]
Tienes el plugin de Automatismos instalado? El plugin de odweather visualiza los datos meteorológicos a través de un dispositivo simulado, que se carga a través de este otro plugin.

**Comment by Juan2005** [comment]
Adjunto captura con el estado de los plugins instalados:

![plugin odweather](https://cloud.githubusercontent.com/assets/12100841/7374619/b5974cfc-eda9-11e4-92ee-e0a9e834c033.png)
![plugins 1](https://cloud.githubusercontent.com/assets/12100841/7374587/973d7cc2-eda9-11e4-9138-5ca8ae435cfd.png)
![plugins automatismo](https://cloud.githubusercontent.com/assets/12100841/7374614/b2259c04-eda9-11e4-9b16-89f553017f38.png)

Gracias por la respuesta y el tiempo.

**Comment by Juan2005** [comment]
No entendía el concepto del dispositivo simulado!!!!
Funciona perfecto. En la opción de mostrar controladores lo puedo ver.
Gracias!!!!

![odweather ok](https://cloud.githubusercontent.com/assets/12100841/7374831/eb20b92a-edaa-11e4-81e2-16142c6b2b28.png)

**Comment by opalenzuela** [comment]
Genial! Doy por cerrado el issue.
